version: '3.8'

services:
  web:
    container_name: blog-ui-prod
    image: blog-ui-prod
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile.prod
    ports:
      - 80:80
