version: '3.8'

services:
  web:
    container_name: blog-ui-dev
    image: blog-ui-dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
